root: true
extends:
  - 'airbnb-typescript'
  - 'plugin:react/jsx-runtime'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: './tsconfig.json'
ignorePatterns:
  - webpack.config.js # Ignore webpack config file